{application,fox,
             [{description,"Matrices in Erlang"},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[fox]},
              {licenses,["Apache 2.0"]},
              {pkg_name,["fox"]},
              {links,[{"GitHub","https://github.com/tanguyl/fox"}]}]}.
